download:
    local_directory: "simulator"
    parameters:
        base_url: "https://raw.githubusercontent.com/ArduPilot/ardupilot/refs/heads/master/Tools/autotest/default_params/"
        file_list:
            - ["copter.parm", "copter.parm"]
    windows:
        base_url: "https://firmware.ardupilot.org/Tools/MissionPlanner/sitl/CopterStable/"
        executable:
            - ["ArduCopter.elf", "ArduCopter.exe"]
        file_list:
            - ["cygatomic-1.dll", "cygatomic-1.dll"]
            - ["cyggcc_s-1.dll", "cyggcc_s-1.dll"]
            - ["cyggcc_s-seh-1.dll", "cyggcc_s-seh-1.dll"]
            - ["cyggomp-1.dll", "cyggomp-1.dll"]
            - ["cygquadmath-0.dll", "cygquadmath-0.dll"]
            - ["cygssp-0.dll", "cygssp-0.dll"]
            - ["cygstdc++-6.dll", "cygstdc++-6.dll"]
            - ["cygwin1.dll", "cygwin1.dll"]
    unix:
        base_url: "https://firmware.ardupilot.org/Copter/stable/SITL_x86_64_linux_gnu/"
        executable:
            - ["arducopter", "arducopter"]
        file_list: []
